import Head from 'next/head'
import Image from 'next/image'
import AboutMe from '../components/AboutMe'
import ContactMe from '../components/ContactMe'
import Intro from '../components/Intro'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Faqih Madani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="profil-blue.png" />
      </Head>

      <Intro />
      <Projects />
      <AboutMe />
      <ContactMe />
    </div>
  )
}
